name: Minimint

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  tester:
    name: 'Test the code'
    strategy:
      matrix:
        python-version: ['3.8', '3.10', '3.12']
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pylint
          pip install pytest-cov
          pip install coveralls
          pip install .
      - name: Pylint
        if: ${{ ( matrix.os != 'windows-latest' ) }}
        run: pylint -E --disable=E1101 py/minimint/*py
      - name: Test
        run:  pytest --cov=minimint -s
      - name: Coveralls
        if: ${{ success() && (matrix.os != 'windows-latest') }}
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
